#!/usr/bin/env osascript

on run argv
  tell application "iTunes"
    set myTrack to name of current track
    set myArtist to artist of current track
    set info to myArtist & " - " & myTrack & "\n"
    set info to info & "[" & player state & "]"
    return info
  end tell
end run
